use_frameworks!

target 'TillhubPointOfSaleSDK_Example' do
  pod 'TillhubPointOfSaleSDK', :path => '../'

  target 'TillhubPointOfSaleSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
