platform :ios, '10.0'
swift_version = '4.2'
use_frameworks!

target 'TillhubPointOfSaleSDK_Example' do
  pod 'TillhubPointOfSaleSDK', :path => '../'

  target 'TillhubPointOfSaleSDK_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
